NO SE PUDO BITACOREAR EN BD EL MENSAJE DE ERROR FUE:    en System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   en System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.Open()
   en System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   en System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   en System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   en System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   en BackEnd.data.ConexionDataContext.Insertar_Bitacora(String cLASE, String mETODO, Nullable`1 tIPO, String dESCRIPCION, String rEQUEST, String rESPONSE) en C:\Proyectos\Moviles\BubbleHouse\BackEnd\BackEnd\data\Conexion.designer.cs:línea 158
   en BackEnd.utils.Utils.crearBitacora(List`1 listaDeErrores, Int16 tipo, String laClase, String elMetodo, String elRequest, String elResponse) en C:\Proyectos\Moviles\BubbleHouse\BackEnd\BackEnd\utils\Utils.cs:línea 18 --> CLASE: LogSesion METODO: Login TIPO 3 DESCRIPCION System.Collections.Generic.List`1[System.String] REQ: {"password":"webada","correo":"victorJS120@gmail.com","origen":"WinUI"} RES {"ListaDeErrores":["Ocurrió un error al crear la sesion"],"Sesion":null,"Resultado":false} FECHA: 02/05/2024 05:23:51 p. m.
